### PR TITLE
IORedis / Memoization Support

### PR DESCRIPTION
**Pull request by blimmer**

### CODE REVIEW

**Comment by blimmer** [comment]
cc @jamesdixon @ronco

**Comment by blimmer** [comment]
I confirmed this linked locally with two of our projects. Works swimmingly.

**Comment by ronco** [comment]
lgtm

**Comment by jamesdixon** [comment]
I second that

**Comment by blimmer** [comment]
cool - will publish 0.4.x. 

thanks!

**Comment by blimmer** [comment]
0.4.0 is available on npm.

**Comment by jamesdixon** [comment]
:+1:

**Pull request merged**
